### ISSUE TITLE
feat ✨ 새로고침시에도 context에 유저정보 유지

### ISSUE THREAD

**Issue by leehyeonseop** [likelion-14-project/lego-market#62]
**구현할 기능**
---
새로고침시에도 유저정보를 context에 유지합니다.
accountname을 localStorage에서 관리하지 않고 context에서 관리합니다.

**구현방법 | 예상 동작**
---

**특이사항**
---

**Comment by Hyebin-woo** [comment]
감사합니다 현섭님!!!
